services:
  app_mngdb:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.mngdb
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_MNGDB_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $APP_MNGDB_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MNGDB_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MNGDB_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8145:8080
